//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComicData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComicDetails
    {
        public System.Guid ComicID { get; set; }
        public Nullable<decimal> Rating { get; set; }
        public string Author { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<decimal> Popularity { get; set; }
        public Nullable<decimal> Hits { get; set; }
        public Nullable<decimal> SubscriptionCount { get; set; }
        public Nullable<decimal> Tweet { get; set; }
        public string Description { get; set; }
        public string ComicName { get; set; }
        public Nullable<int> ComicIDOrg { get; set; }
    }
}
