//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComicData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComicTable
    {
        public System.Guid ComicID { get; set; }
        public string ComicName { get; set; }
        public int SiteID { get; set; }
        public string URL { get; set; }
        public string Description { get; set; }
        public Nullable<int> Rating { get; set; }
    
        public virtual ComicTable ComicTable1 { get; set; }
        public virtual ComicTable ComicTable2 { get; set; }
    }
}
