//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComicData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteCategory
    {
        public int SiteID { get; set; }
        public int CategoryID { get; set; }
        public string Description { get; set; }
        public string URL { get; set; }
        public string CategoryName { get; set; }
    }
}
